######################################################################
# Automatically generated by qmake (3.0) sáb dez 10 17:35:05 2016
######################################################################
TEMPLATE = lib
CONFIG += plugin
CONFIG += no_plugin_name_prefix

INCLUDEPATH += .
INCLUDEPATH += ../../../include
INCLUDEPATH += ../../../deps/include

TARGET = mysql
DESTDIR = ../../../clib/charon

LIBS += -L ../../../deps -llua -lm -lmysqlclient -ldl

# Input
SOURCES += host.c luamysql.c
