######################################################################
# Automatically generated by qmake (3.0) sáb nov 5 14:42:37 2016
######################################################################

TEMPLATE = lib
CONFIG += plugin
CONFIG += no_plugin_name_prefix

INCLUDEPATH += .
INCLUDEPATH += ../../../vendors/include/luajit-2.0/

TARGET = json

DESTDIR = ../../../clib/

# Input
HEADERS += dtoa_config.h fpconv.h strbuf.h
SOURCES += lua_cjson.c strbuf.c fpconv.c # dtoa.c g_fmt.c 
