######################################################################
# Automatically generated by qmake (3.0) dom jan 24 22:51:13 2016
######################################################################
TEMPLATE = lib
CONFIG += plugin
CONFIG += no_plugin_name_prefix

INCLUDEPATH += .
INCLUDEPATH += ../../../include
INCLUDEPATH += ../../../deps/include

TARGET = pgsql
DESTDIR = ../../../clib

LIBS += -L ../../../deps -llua -lpq

# Input
HEADERS += pgsql.h
SOURCES += pgsql.c
