######################################################################
# Automatically generated by qmake (3.0) qua mar 30 21:35:45 2016
######################################################################

TEMPLATE = subdirs
SUBDIRS = lsqlite3 \
          json \
          luasql/sqlite3


linux:SUBDIRS += pgsql \
                 mysql \
                 luasql/mysql \
                 luasql/postgres
