local M = {}

 -- application
 M['jar']  = 'application/java-archive'
 M['war']  = 'application/java-archive'
 M['ear']  = 'application/java-archive'
 M['hqx']  = 'application/mac-binhex40'
 M['doc']  = 'application/msword'
 M['pdf']  = 'application/pdf'
 M['ps']   = 'application/postscript'
 M['eps']  = 'application/postscript'
 M['ai']   = 'application/postscript'
 M['rtf']  = 'application/rtf'
 M['xls']  = 'application/vnd.ms-excel'
 M['ppt']  = 'application/vnd.ms-powerpoint'
 M['wmlc'] = 'application/vnd.wap.wmlc'
 M['kml']  = 'application/vnd.google-earth.kml+xml'
 M['kmz']  = 'application/vnd.google-earth.kmz'
 M['7z']   = 'application/x-7z-compressed'
 M['cco']  = 'application/x-cocoa'
 M['jnlp'] = 'application/x-java-jnlp-file'
 M['run']  = 'application/x-makeself'
 M['pl']   = 'application/x-perl'
 M['pm']   = 'application/x-perl'
 M['prc']  = 'application/x-pilot'
 M['pdb']  = 'application/x-pilot'
 M['rar']  = 'application/x-rar-compressed'
 M['rpm']  = 'application/x-redhat-package-manager'
 M['sea']  = 'application/x-sea'
 M['swf']  = 'application/x-shockwave-flash'
 M['sit']  = 'application/x-stuffit'
 M['js']   = 'application/x-javascript'
 M['atom'] = 'application/atom+xml'
 M['rss']  = 'application/rss+xml'
 M['tcl']  = 'application/x-tcl'
 M['tk']   = 'application/x-tcl'
 M['der']  = 'application/x-x509-ca-cert'
 M['pem']  = 'application/x-x509-ca-cert'
 M['crt']  = 'application/x-x509-ca-cert'
 M['xpi']  = 'application/x-xpinstall'
 M['xhtml']= 'application/xhtml+xml'
 M['zip']  = 'application/zip'

 -- audio
 M['kar']  = 'audio/midi'
 M['mpeg'] = 'audio/mp3'
 M['mid']  = 'audio/midi'
 M['midi'] = 'audio/midi'
 M['ogg']  = 'audio/ogg'
 M['m4a']  = 'audio/x-m4a'
 M['ra']   = 'audio/x-realaudio'

 -- image
 M['bmp']   = 'image/x-icon'
 M['ico']   = 'image/x-ms-bmp'
 M['gif']   = 'image/gif'
 M['jng']   = 'image/jng'
 M['jpg']   = 'image/jpeg'
 M['jpeg']  = 'image/jpeg'
 M['png']   = 'image/png'
 M['svg']   = 'image/svg+xml'
 M['svgz']  = 'image/svg+xml'
 M['tif']   = 'image/tif'
 M['tiff']  = 'image/tiff'
 M['webp']  = 'image/webp'
 M['wbmp']  = 'image/vnd.wap.wbmp'

 -- octet-stream
 M['bin']   = 'application/octet-stream'
 M['exe']   = 'application/octet-stream'
 M['dll']   = 'application/octet-stream'
 M['deb']   = 'application/octet-stream'
 M['dmg']   = 'application/octet-stream'
 M['eot']   = 'application/octet-stream'
 M['iso']   = 'application/octet-stream'
 M['img']   = 'application/octet-stream'
 M['msi']   = 'application/octet-stream'
 M['msp']   = 'application/octet-stream'
 M['msm']   = 'application/octet-stream'

 -- text
 M['css']   = 'text/css'
 M['jad']   = 'text/vnd.sun.j2me.app-descriptor'
 M['html']  = 'text/html'
 M['htm']   = 'text/html'
 M['mml']   = 'text/mathml'
 M['shtml'] = 'text/html'
 M['text']  = 'text/plain'
 M['xml']   = 'text/xml'
 M['wml']   = 'text/vnd.wap.wml'
 M['htc']   = 'text/x-component'
 M['htm']   = 'text/html'

 -- video
 M['asf']   = 'video/x-ms-asf'
 M['asx']   = 'video/x-ms-asf'
 M['avi']   = 'video/x-msvideo'
 M['3gpp']  = 'video/3gpp'
 M['3gp']   = 'video/3gpp'
 M['flv']   = 'video/x-flv'
 M['x-m4v'] = 'video/m4v'
 M['mng']   = 'video/x-mng'
 M['mp4']   = 'video/mp4'
 M['mpg']   = 'video/mpg'
 M['mpeg']  = 'video/mpeg'
 M['mov']   = 'video/quicktime'
 M['webm']  = 'video/webm'
 M['wmv']   = 'video/x-ms-wmv'

return M
