######################################################################
# Automatically generated by qmake (3.0) sex nov 11 10:05:45 2016
######################################################################

TEMPLATE = app
TARGET = ../../../bin/sqlite3
INCLUDEPATH += .

# Input
HEADERS += sqlite3.h sqlite3ext.h
SOURCES += shell.c sqlite3.c

LIBS += -ldl
