######################################################################
# Automatically generated by qmake (3.0) dom jan 24 22:51:13 2016
######################################################################
TEMPLATE = lib
INCLUDEPATH += .
INCLUDEPATH += ../../include
TARGET = oberon
DESTDIR = ../../shared

# Input
SOURCES += ../../src/oberon/*.cpp
