if(EXISTS /opt/local/include)
  include_directories( /opt/local/include )
endif()
if(EXISTS /opt/homebrew/include)
  include_directories( /opt/homebrew/include )
endif()

if(EXISTS /opt/homebrew/lib)
  link_directories( /opt/homebrew/lib )
endif()
if(EXISTS /opt/local/lib)
  link_directories( /opt/local/lib )
endif()

if( LUA_POSTGRES )
  if(EXISTS /opt/local/include/postgresql13)
    include_directories( /opt/local/include/postgresql13 )
  endif()
  if(EXISTS /opt/local/lib/postgresql13)
    link_directories( /opt/local/lib/postgresql13 )
  endif()
endif()

if( LUA_MYSQL )
  if(EXISTS /opt/local/include/mysql57)
    include_directories( /opt/local/include/mysql57 )
  endif()
  if(EXISTS /opt/local/lib/mysql57/mysql)
    link_directories( /opt/local/lib/mysql57/mysql )
  endif()
endif()
