cp vendors/*.dll bin
cp $1/bin/libgcc_s_dw2-1.dll bin
cp $1/bin/libstdc++-6.dll bin
cp $1/bin/libwinpthread-1.dll bin
cp $1/bin/Qt5Concurrent.dll bin
cp $1/bin/Qt5Concurrentd.dll bin
cp $1/bin/Qt5Core.dll bin
cp $1/bin/Qt5Cored.dll bin
cp $1/bin/Qt5Network.dll bin
cp $1/bin/Qt5Networkd.dll bin
