######################################################################
# Automatically generated by qmake (3.0) qua mar 30 16:12:33 2016
######################################################################

TEMPLATE =lib
TARGET = oberon
INCLUDEPATH += ../../include
DESTDIR = ../../shared

# Input
SOURCES += *.cpp
